[package]
name = "carpet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
debug = 1

[dependencies]
orbtk = { git = "https://github.com/trickypr/orbtk.git", branch = "fix_slider" }
lazy_static = "1.4.0"
rodio = "0.14.0"

# Config
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Linux only rust dependancies:
[target.'cfg(target_os = "linux")'.dependencies]
xdg = "2.4"
